apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-event-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.2"
  ACCOUNT: "aws:908671954593"
  APP_NAME: "go-worker-event.arch-eks-01-02"
  PORT: "7007"
  ENV: "dev"

  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "warning" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector.default.svc.cluster.local:4317"

  OTEL_METRICS: "true"
  OTEL_STDOUT_TRACER: "false"
  OTEL_TRACES: "true"

  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/mnt/c/Eliezer/log/go-worker-event.log"

  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "SASL_SSL"
  KAFKA_MECHANISM: "SCRAM-SHA-512"
  KAFKA_CLIENT_ID: "GO-WORKER-EVENT-01"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "1"
  KAFKA_GROUP_ID: "GROUP-WORKER-EVENT-01"
  TOPIC_EVENT_00: "topic.clearance.01"

  KAFKA_BROKER_1: "b-1.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096" 
  KAFKA_BROKER_2: "b-3.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096" 
  KAFKA_BROKER_3: "b-2.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
