apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-go-worker-event
  namespace: test-a
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/default-backend: "svc-go-worker-event"
    nginx.ingress.kubernetes.io/proxy_body_timeout: "300"
    nginx.ingress.kubernetes.io/proxy_connect_timeout: "300"
    nginx.ingress.kubernetes.io/proxy_read_timeout: "300"
    nginx.ingress.kubernetes.io/proxy_send_timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: go-worker-event.architecture.caradhras.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-go-worker-event
              port:
                number: 7007
